### Importing libraries and reading csv file

In [2]:
import numpy as np 
import pandas as pd 
import sklearn 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split # Import train_test_split function 
dataset=pd.read_csv("mnist.csv")

In [3]:
print(dataset) 

       label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
5          0       0       0       0       0       0       0       0       0   
6          7       0       0       0       0       0       0       0       0   
7          3       0       0       0       0       0       0       0       0   
8          5       0       0       0       0       0       0       0       0   
9          3       0       0       0       0       0       0       0       0   
10         8       0       0       0       0       0       0       0       0   
11         9       0       0       0    

In [4]:
dataset.shape

(42000, 785)

###  features

In [5]:
x=dataset.iloc[:15000,1:dataset.index[-1]+1].values  #features 
print(x) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
x.shape

(15000, 784)

### Target variable

In [7]:
y=dataset.iloc[:15000,0].values #target 
print(y)

[1 0 1 ... 8 9 6]


In [8]:
#Spilt dataset into training set and test set 
X_train,X_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=1) # 70% training and 30% test

### KNN method with n=3 with default distance metric

In [10]:
classifier= KNeighborsClassifier(n_neighbors=3) #3
classifier.fit(x,y) #training
classifier.fit(X_train,y_train)
print(X_test)
#print(y_test)
y_predict=classifier.predict(X_test) #testing
print(y_predict)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[3 5 3 ... 0 4 3]


In [11]:
#accuracy of predicted labels
from sklearn.metrics import accuracy_score 
accuracy_score(y_test,y_predict) 

0.9486666666666667

### Manhattan distance

In [12]:
classifier= KNeighborsClassifier(n_neighbors=3,metric="manhattan") #3
classifier.fit(x,y) #training
classifier.fit(X_train,y_train)
print(X_test)
#print(y_test)
y_predict=classifier.predict(X_test) #testing
print(y_predict)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[3 5 3 ... 0 4 3]


In [13]:
accuracy_score(y_test,y_predict) 

0.9422222222222222

In [14]:
classifier= KNeighborsClassifier(n_neighbors=3,metric="chebyshev") #3
classifier.fit(x,y) #training
classifier.fit(X_train,y_train)
print(X_test)
#print(y_test)
y_predict=classifier.predict(X_test) #testing
print(y_predict)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[3 3 3 ... 0 4 3]


In [15]:
accuracy_score(y_test,y_predict) 

0.6833333333333333

In [16]:
classifier= KNeighborsClassifier(n_neighbors=5) #3
classifier.fit(x,y) #training
classifier.fit(X_train,y_train)
print(X_test)
#print(y_test)
y_predict=classifier.predict(X_test) #testing
print(y_predict)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[3 5 3 ... 0 4 3]


In [17]:
accuracy_score(y_test,y_predict) 

0.9475555555555556

### Default distance metric gives higher accuracy than others.Though this accuracy can be improved by various methods like using CNN.KNN gives a accuracy of about 96%.