In [1]:
#Importing the required libraries
import numpy as np
from scipy.stats import mode
import pandas as pd 
from numpy.random import randint

In [2]:
#reading the dataset
dataset=pd.read_csv("mnist.csv")

In [3]:
#Function to calculate Euclidean Distance
def eucledian_distance(p1,p2):
    dist = np.sqrt(np.sum((p1-p2)**2))
    return dist

In [4]:
#Function to Predict using KNN
def predict(X_train, y_train , X_test, k):
    y_pred = []
     
    #Loop through the Datapoints to be classified
    for item in X_test: 
         
        #list to store distance from each point
        dist = []
        
        #Loop through each training Data
        for j in range(len(X_train)): 
            distances = eucledian_distance(np.array(X_train[j,:]) , item) 
            #Calculating the distance
            dist.append(distances) 
        dist = np.array(dist) 
         
        #Sorting the array while preserving the index
        #Keeping the first K neighbors
        dist = np.argsort(dist)[:k] 
         
        #Labels of the K neighbors from above
        labels = y_train[dist]
        
        lab = mode(labels) 
        lab = lab.mode[0]
        y_pred.append(lab)
 
    return y_pred

In [11]:
x=dataset.iloc[:15000,1:dataset.index[-1]+1].values  #features 
print(x) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
x.shape

(15000, 784)

In [13]:
y=dataset.iloc[:15000,0].values #target 
print(y)

[1 0 1 ... 8 9 6]


In [14]:
y.shape

(15000,)

In [15]:
#Spilt dataset into training set and test set 
from sklearn.model_selection import train_test_split # Import train_test_split function 
X_train,X_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=1) # 70% training and 30% test

In [16]:
y_pred = predict(X_train,y_train,X_test,3)

In [17]:
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0

In [21]:
acc=accuracy_metric(y_test,y_pred)
print("Accuracy of using KNN method using Euclidean with 15000 samples is %",acc)

Accuracy of using KNN method using Eucli with 15000 samples is % 94.86666666666666
